// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binary flavor used by the native Wayland capture helper. `data` is base64
 * so large images never become JSON arrays of individual numbers.
 */
export type CapturedFlavor = { mime: string, data: string, };
