// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

/**
 * Pushed to subscribed clients. The warm UI keeps its list current from these,
 * so opening the popup needs no query at all — that is what makes it feel
 * instant.
 */
export type Event = { "event": "added", item: Item, } | { "event": "updated", item: Item, } | { "event": "removed", id: number, } | { "event": "cleared" } | { "event": "toggle" } | { "event": "notice", message: string, };
