// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

/**
 * A history row as the UI sees it. Deliberately excludes payload bytes: the
 * list renders from `preview` alone, and full content is fetched only when an
 * item is actually pasted.
 */
export type Item = { id: number, kind: Kind, 
/**
 * Truncated, single-line, safe to render directly.
 */
preview: string, byte_size: number, created_at: number, last_used_at: number, use_count: number, pinned: boolean, favorite: boolean, 
/**
 * Looked like a credential. Render blurred; excluded from the search index.
 */
sensitive: boolean, source_app: string | null, 
/**
 * Every MIME type captured for this one copy, e.g. `["text/html", "UTF8_STRING"]`.
 */
mimes: Array<string>, };
