// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a clipboard item fundamentally is. Drives the icon and the preview
 * renderer; derived once at capture time rather than re-sniffed per render.
 */
export type Kind = "text" | "url" | "code" | "color" | "html" | "image" | "files";
