// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Request = { "op": "recent", limit: number, } | { "op": "search", query: string, limit: number, } | { "op": "paste", id: number, plain: boolean, } | { "op": "copy", id: number, } | { "op": "delete", id: number, } | { "op": "pin", id: number, pinned: boolean, } | { "op": "favorite", id: number, favorite: boolean, } | { "op": "clear_all" } | { "op": "toggle_popup" } | { "op": "focus_popup" } | { "op": "subscribe" } | { "op": "ping" };
