// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";

export type Response = { "type": "items", items: Array<Item>, } | { "type": "ok" } | { "type": "error", message: string, } | { "type": "pong" } | { "type": "thumbnail", data: string, };
